version: '3.9'

services:
  app:
    container_name: FastAPI
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    ports:
      - "9004:9004"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9004

#version: '3'
#services:
#  python3:
#    restart: always
#    build: .
#    container_name: 'python3'
#    working_dir: '/root/'
#    tty: true
#    volumes:
#      - ./src:/root/src
#    ports:
#      - "9004:9004"
