version: '3.9'

services:
  app:
    container_name: FastAPI
    build: .
    volumes:
      - ./src:/app
    ports:
      - "9004:9004"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9004